WebApplication_StockDataFixx/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using WebApplication_StockDataFixx.Database;
using WebApplication_StockDataFixx.Models.Domain;
using System.Linq;
using WebApplication_StockDataFixx.Models;

namespace WebApplication_StockDataFixx.Controllers
{
    public class AdminController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly PMIDbContext _dbContext;

        public AdminController(IConfiguration configuration, IWebHostEnvironment webHostEnvironment, PMIDbContext dbContext)
        {
            _configuration = configuration;
            _webHostEnvironment = webHostEnvironment;
            _dbContext = dbContext;
        }

        public IActionResult DashboardAdmin()
        {
            var users = _dbContext.UserTbs.ToList();
            return View(users);
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            var levels = _dbContext.SecurityTbs.ToList();
            ViewBag.Levels = levels;

            return View();
        }


        public IActionResult GenerateToken()
        {
            return View();
        }

        public IActionResult AllView()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddUser(AddUserRequest addUserRequest)
        {
            if (ModelState.IsValid)
            {
                // Konversi AddUserRequest ke UserTb
                var newUser = new UserTb
                {
                    LevelId = addUserRequest.LevelId,
                    UserId = addUserRequest.UserId,
                    Username = addUserRequest.Username,
                    Password = addUserRequest.Password,
                    JobId = addUserRequest.JobId,
                    PlantId = addUserRequest.PlantId
                };

                _dbContext.UserTbs.Add(newUser);
                _dbContext.SaveChanges();
                return RedirectToAction("DashboardAdmin");
            }

            var levels = _dbContext.SecurityTbs.ToList();
            ViewBag.Levels = levels;

            return View(addUserRequest);
        }


        [HttpPost]
        public IActionResult DeleteUser(string userId)
        {
            var user = _dbContext.UserTbs.FirstOrDefault(u => u.UserId == userId);
            if (user != null)
            {
                _dbContext.UserTbs.Remove(user);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("DashboardAdmin");
        }
    }
}

WebApplication_StockDataFixx/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using WebApplication_StockDataFixx.Models.Domain;
using Newtonsoft.Json;
using WebApplication_StockDataFixx.Database;
using Microsoft.IdentityModel.Tokens;
using System.Globalization;
using NPOI.SS.Formula.Functions;
using DocumentFormat.OpenXml.Vml.Spreadsheet;
using DocumentFormat.OpenXml.Bibliography;
using System.Collections;
using DocumentFormat.OpenXml.Spreadsheet;
using System.Reflection.Metadata;
using ClosedXML.Excel;
using ExcelDataReader;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace WebApplication_StockDataFixx.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly PMIDbContext _dbContext;

        public WarehouseController(IConfiguration configuration, IWebHostEnvironment webHostEnvironment, PMIDbContext dbContext)
        {
            _configuration = configuration;
            _webHostEnvironment = webHostEnvironment;
            _dbContext = dbContext;
        }

        // Method to display the DashboardWarehouse page
        [HttpGet]
        public ActionResult DashboardWarehouse()
        {
            return View();
        }


        // Method to display the UploadDataWarehouse page
        [HttpGet]
        public ActionResult UploadDataWarehouse()
        {
            // Tampilkan halaman upload file warehouse
            return View();
        }

        public ActionResult DownloadPageWrh()
        {
            
            return View();
        }


// =============================================================================================== READ DATA =============================================================================================== //



        // Main Method Report 
        // Method to display based on access plant, storage type dll..
        [HttpGet]
        public ActionResult ReportWarehouse(string serialNo, string selectedType, string selectedMonth)
        {
            List<WarehouseItem> data;

            string accessPlant = HttpContext.Session.GetString("AccessPlant") ?? "";

            // Fetch data based on the selectedType (VMI or NonVMI) and selectedMonth
            if (selectedType == "VMI")
            {
                data = GetDataFromDatabase(serialNo, Isvmi: true, accessPlant);
            }
            else if (selectedType == "NON VMI")
            {
                data = GetDataFromDatabase(serialNo, Isvmi: false, accessPlant);
            }
            else
            {
                data = GetDataFromDatabase(serialNo, Isvmi: null, accessPlant); // Fetch all data
            }

            if (!string.IsNullOrEmpty(accessPlant))
            {
                // Filter data based on the AccessPlant value
                data = data.Where(w => w.AccessPlant == accessPlant).ToList();
            }

            // Check if there are any elements in the filtered data
            if (data.Any())
            {
                // Jika selectedMonth tidak ada atau kosong, ambil data terbaru seperti di ReportProduction
                if (string.IsNullOrEmpty(selectedMonth) || selectedMonth == "Latest Uploaded Month")
                {
                    // Filter data based on the latest upload month and year
                    var latestUploadDate = data.Max(item => item.LastUpload.Date);
                    data = data.Where(wi => wi.LastUpload.Year == latestUploadDate.Year && wi.LastUpload.Month == latestUploadDate.Month && wi.AccessPlant == accessPlant)
                               .ToList();
                }
                else
                {
                    // Ambil data berdasarkan bulan dan tahun yang dipilih pada selectedMonth
                    if (DateTime.TryParseExact(selectedMonth, "yyyy-MM", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime parsedMonth))
                    {
                        data = data.Where(w => w.LastUpload.Year == parsedMonth.Year && w.LastUpload.Month == parsedMonth.Month && w.AccessPlant == accessPlant)
                                   .ToList();
                    }
                    else
                    {
                        // Handle kesalahan jika selectedMonth tidak valid
                        // Misalnya, lempar pengecualian atau kembalikan data kosong, sesuai dengan kebutuhan Anda.
                        throw new ArgumentException("selectedMonth is not in the correct format.");
                    }
                }
            }
            else
            {
                // Handle the case where there are no elements in the filtered data
            }

            ViewBag.SerialNo = serialNo;
            ViewBag.LastUpload = GetUniqueMonths(accessPlant, selectedType);

            return View(data);
        }

        // Temp Method Report 
        [HttpGet]
        public ActionResult ReportTempWarehouse(string serialNo, string selectedType, string selectedMonth)
        {
            List<TempWarehouseItem> data;

            string accessPlant = HttpContext.Session.GetString("AccessPlant") ?? "";

            // Fetch data based on the selectedType (VMI or NonVMI) and selectedMonth
            if (selectedType == "VMI")
            {
                data = GetDataFromDatabaseTemp(serialNo, Isvmi: true, accessPlant);
            }
            else if (selectedType == "NON VMI")
            {
                data = GetDataFromDatabaseTemp(serialNo, Isvmi: false, accessPlant);
            }
            else
            {
                data = GetDataFromDatabaseTemp(serialNo, Isvmi: null, accessPlant); // Fetch all data
            }

            if (!string.IsNullOrEmpty(accessPlant))
            {
                // Filter data based on the AccessPlant value
                data = data.Where(w => w.AccessPlant == accessPlant).ToList();
            }

            // Check if there are any elements in the filtered data
            if (data.Any())
            {
                // Jika selectedMonth tidak ada atau kosong, ambil data terbaru seperti di ReportProduction
                if (string.IsNullOrEmpty(selectedMonth) || selectedMonth == "Latest Uploaded Month")
                {
                    // Filter data based on the latest upload month and year
                    var latestUploadDate = data.Max(item => item.LastUpload.Date);
                    data = data.Where(wi => wi.LastUpload.Year == latestUploadDate.Year && wi.LastUpload.Month == latestUploadDate.Month && wi.AccessPlant == accessPlant)
                               .ToList();
                }
                else
                {
                    // Ambil data berdasarkan bulan dan tahun yang dipilih pada selectedMonth
                    if (DateTime.TryParseExact(selectedMonth, "yyyy-MM", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime parsedMonth))
                    {
                        data = data.Where(w => w.LastUpload.Year == parsedMonth.Year && w.LastUpload.Month == parsedMonth.Month && w.AccessPlant == accessPlant)
                                   .ToList();
                    }
                    else
                    {
                        // Handle kesalahan jika selectedMonth tidak valid
                        // Misalnya, lempar pengecualian atau kembalikan data kosong, sesuai dengan kebutuhan Anda.
                        throw new ArgumentException("selectedMonth is not in the correct format.");
                    }
                }
            }
            else
            {
                // Handle the case where there are no elements in the filtered data
            }

            ViewBag.SerialNo = serialNo;
            ViewBag.LastUpload = GetUniqueMonthsTemp(accessPlant, selectedType);

            return View(data);
        }

        // Jika Menggunakan Kolom Last Upload Main
        private IEnumerable<DateTime> GetUniqueMonths(string accessPlant, string selectedType)
        {
            var uniqueMonths = _dbContext.WarehouseItems
                .Where(w => w.AccessPlant == accessPlant && (selectedType == "VMI" ? w.Isvmi == "VMI" : w.Isvmi == "NonVMI"))
                .Select(w => w.LastUpload.Date)
                .Distinct()
                .ToList();

            return uniqueMonths;
        }

        // Jika Menggunakan Kolom Last Upload Temp
        private IEnumerable<DateTime> GetUniqueMonthsTemp(string accessPlant, string selectedType)
        {
            var uniqueMonths = _dbContext.TempWarehouseItems
                .Where(w => w.AccessPlant == accessPlant && (selectedType == "VMI" ? w.Isvmi == "VMI" : w.Isvmi == "NonVMI"))
                .Select(w => w.LastUpload.Date)
                .Distinct()
                .ToList();

            return uniqueMonths;
        }

        // Method to Get Data from Database Main
            private List<WarehouseItem> GetDataFromDatabase(string serialNo, bool? Isvmi, string accessPlant)
        {
            // Fetch data from the warehouse database (adjust this based on your actual database context)
            var data = _dbContext.WarehouseItems.AsQueryable();

            if (!string.IsNullOrEmpty(serialNo))
            {
                data = data.Where(w => w.SerialNo == serialNo);
            }

            if (Isvmi.HasValue)
            {
                data = data.Where(w => w.Isvmi == (Isvmi.Value ? "VMI" : "NonVMI"));
            }

            if (!string.IsNullOrEmpty(accessPlant))
            {
                data = data.Where(w => w.AccessPlant == accessPlant);
            }

            return data.OrderBy(w => w.SerialNo).ToList();
        }


        // Method to Get Data from Database Temp
        private List<TempWarehouseItem> GetDataFromDatabaseTemp(string serialNo, bool? Isvmi, string accessPlant)
        {

WebApplication_StockDataFixx/Views/Admin/AddUser.cshtml
@model WebApplication_StockDataFixx.Models.Domain.UserTb

@{
    ViewData["Title"] = "Add User";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="container-fluid p-0">
    <div class="row">
        <div class="col-md-6">
            <div class="header-tittle" style="margin-bottom: 25px;">
                <h2>Add User</h2>
                <p>Welcome Admin Stock Taking</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="text-right ml-auto">
                <!-- Gunakan class ml-auto di sini -->
                <div class="button-header">
                    <a class="button" asp-controller="Admin" asp-action="DashboardAdmin">
                        View Data
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row  mb-10" >
                <div class="d-flex justify-content-between AddUserImg">
                    <div class="col-md-6" style="margin-top:40px;">
                        <form asp-action="AddUser" method="post" id="userForm">
                            <div class="form-group">
                                <label asp-for="UserId">User ID</label>
                                <input asp-for="UserId" class="form-control" />
                                <span asp-validation-for="UserId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Username">Username</label>
                                <input asp-for="Username" class="form-control" />
                                <span asp-validation-for="Username" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Password">Password</label>
                                <input asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LevelId">Level</label>
                                <select asp-for="LevelId" class="form-control">
                                    @foreach (var level in ViewBag.Levels)
                                    {
                                        <option value="@level.LevelId">@level.LevelDesc</option>
                                    }
                                </select>
                                <span asp-validation-for="LevelId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="JobId">Job ID</label>
                                <input asp-for="JobId" class="form-control" />
                                <span asp-validation-for="JobId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PlantId">Plant ID</label>
                                <input asp-for="PlantId" class="form-control" />
                                <span asp-validation-for="PlantId" class="text-danger"></span>
                            </div>
                            <div class="btn-addAdmin">
                                <button type="submit" class="btn" style="margin-bottom: 30px;">Add User</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <img src="~/images/img/LoginScreen.png" width="450" height="400" class="imgAddUser" />
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>  

WebApplication_StockDataFixx/Views/Admin/AllView.cshtml
@{
    ViewData["Title"] = "AllView";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

    <div class="container-fluid p-0"> 
        <img src="/images/img/bgAllView.jpeg" class="bgAllView">
    <div class="row">
        <div class="col-md-6">
            <div class="header-tittle" style="margin-bottom: 20px;color: #1D5D9B;">
                <h2>ALL VIEW</h2>
                <p>To maintenance all data , please select this role user :</p>
            </div>
        </div>
        <div class="col-md-6">
        </div>
    </div>

        <div class="row AllView">
            <div class="col-md-4">
                <div class="AllProd">
                    <a asp-controller ="Production" asp-action="DashboardProduction">
                        <div class="card card-AllView" style="border-radius: 15px;">                           
                            <img src="/images/img/productionAllView.jpeg"/>
                            <p>PRODUCTION</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="AllWrh">
                <a asp-controller="Warehouse" asp-action="DashboardWarehouse">
                    <div class="card card-AllView" style="border-radius: 15px;">
                        <img src="/images/img/warehouseAllView.jpeg" />
                        <p>WAREHOUSE</p>
                    </div>
                </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="AllMng">
                <a asp-controller="Management" asp-action="DashboardManagement">
                    <div class="card card-AllView" style="border-radius: 15px;">
                        <img src="/images/img/managementAllVie.jpeg" />
                        <p>MANAGEMENT</p>
                    </div>
                </a>
                </div>
            </div>
        </div>
    </div>

WebApplication_StockDataFixx/Views/Admin/DashboardAdmin.cshtml
@model List<WebApplication_StockDataFixx.Models.Domain.UserTb>

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<div class="container-fluid p-0">
    <div class="row">
        <div class="col-md-6">
            <div class="header-tittle" style="margin-bottom: 25px;">
                <h2>Dashboard</h2>
                <p>Welcome Admin Stock Taking</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="text-right ml-auto">
                <!-- Gunakan class ml-auto di sini -->
                <div class="button-header">
                    <a class="button" asp-controller="Admin" asp-action="AddUser">
                        <i class="fas fa-plus" style=""></i>
                        Add User
                    </a>
                </div>
            </div>
        </div>
    </div>


    <div class="row  mb-10" style="margin-top:40px;">
        <div class="col-md-12">
            <table class="display" width="100%" height="100%">
                <thead>
                    <tr style="color: darkgrey;">
                        <th>User ID</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>Job ID</th>
                        <th>Plant ID</th>
                        <th>Stat</th>
                        <th>Created Date Time</th>
                        <th>Last Deleted Date Time</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model)
                    {
                        <tr>
                            <td>@user.UserId</td>
                            <td>@user.Username</td>
                            @*<td>@user.Password</td>*@
                            <td>
                                <i class="fas fa-eye" style="cursor: pointer;" onclick="togglePassword(this)"></i>
                                <span style="display: none;">@user.Password</span>
                            </td>
                            <td>@user.JobId</td>
                            <td>@user.PlantId</td>
                            <td>@user.Stat</td>
                            <td>@user.CreatedDateTime</td>
                            <td>@user.DeletedDateTime</td>
                            <td>
                                <form asp-action="DeleteUser" asp-route-userId="@user.UserId" method="post" onsubmit="return confirm('Are you sure you want to delete this user?');">
                                    <button type="submit" class="btn btn-link text-danger" title="Delete">
                                        <i class="fas fa-trash"></i> <!-- Ini adalah ikon tong sampah dari Font Awesome -->
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

WebApplication_StockDataFixx/Views/Admin/GenerateToken.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<style type="text/css">
    .bgimg {
        margin-right: -20px;
        margin-left: -20px;
        margin-bottom: -20px;
        margin-top: -45px;
        height: 100%;
        background-position: center;
        background-size: cover;
        position: relative;
        color: white;
        font-family: "Courier New", Courier, monospace;
        font-size: 25px;
    }

        .bgimg img {
            position: relative;
            width: 1151px;
            height: 596px;
            opacity: 85%;
            /*height: 1000px;*/
        }

    /* Position text in the top-left corner */
    .topleft {
        position: absolute;
        top: 20px;
        left: 16px;
        text-shadow: 2px 2px #000;
    }

    /* Position text in the bottom-left corner */
    .bottomleft {
        position: absolute;
        bottom: 20px;
        left: 16px;
        text-shadow: 2px 2px #000;
    }

    /* Position text in the middle */
    .middle {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
        text-shadow: 2px 2px #000;
    }

    /* Style the <hr> element */
    hr {
        margin: auto;
        width: 40%;
    }
</style>

<script type="text/javascript">
    // Set the date we're counting down to
    var countDownDate = new Date("Dec 23, 2023 15:37:25").getTime();

    // Update the count down every 1 second
    var countdownfunction = setInterval(function () {

        // Get todays date and time
        var now = new Date().getTime();

        // Find the distance between now an the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Output the result in an element with id="demo"
        document.getElementById("demo").innerHTML = days + "d " + hours + "h "
            + minutes + "m " + seconds + "s ";

        // If the count down is over, write some text
        if (distance < 0) {
            clearInterval(countdownfunction);
            document.getElementById("demo").innerHTML = "EXPIRED";
        }
    }, 1000);
</script>

<div class="bgimg">
    <img src="/images/img/comingsoon2.png" />
    <div class="topleft">
        <p>Panasonic</p>
    </div>
    <div class="middle">
        <h1>COMING SOON</h1>
        <hr>
        <p id="demo" style="font-size:30px"></p>
    </div>
    <div class="bottomleft">
        <p>Stock Taking Data App</p>
    </div>
</div>